# Phase 4.1 - Enhanced Gateway Security Configuration
# Advanced security plugins and configurations for Kong Gateway

# Security Headers Plugin Configuration
security_headers_config:
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' ws: wss:; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"
  x_frame_options: "SAMEORIGIN"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  strict_transport_security: "max-age=31536000; includeSubDomains; preload"
  x_permitted_cross_domain_policies: "none"

# Advanced Rate Limiting Rules
rate_limiting_rules:
  # Public endpoints (less restrictive)
  public_endpoints:
    minute: 200
    hour: 2000
    day: 20000
    
  # Authenticated endpoints (moderate)
  authenticated_endpoints:
    minute: 500
    hour: 5000
    day: 50000
    
  # Admin endpoints (most restrictive)
  admin_endpoints:
    minute: 50
    hour: 500
    day: 5000

# CORS Security Configuration
cors_security:
  allowed_origins:
    - "https://app.yourcompany.com"
    - "https://admin.yourcompany.com"
    - "https://mobile.yourcompany.com"
    - "http://localhost:3000"    # Development only
    - "http://localhost:5173"    # Vite dev server
  allowed_methods:
    - "GET"
    - "POST" 
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-API-Key"
    - "X-Requested-With"
    - "X-CSRF-Token"
  exposed_headers:
    - "X-RateLimit-Limit"
    - "X-RateLimit-Remaining"
    - "X-Request-ID"
  max_age: 86400  # 24 hours
  credentials: true

# IP Allowlist Configuration
ip_security:
  # Production allowlist (adjust for your environment)
  allowed_ips:
    - "10.0.0.0/8"           # Internal network
    - "172.16.0.0/12"        # Docker networks
    - "192.168.0.0/16"       # Local networks
    - "127.0.0.1"            # Localhost
    
  # Office/VPN networks (examples)
  # - "203.0.113.0/24"       # Office network
  # - "198.51.100.0/24"      # VPN network
  
  # Blocked IPs (examples)
  blocked_ips: []
    # - "192.0.2.100"         # Blocked IP example

# JWT Security Configuration
jwt_security:
  algorithms:
    - "HS256"
    - "RS256"
  claims_to_verify:
    - "exp"     # Expiration time
    - "iat"     # Issued at
    - "nbf"     # Not before
    - "aud"     # Audience
    - "iss"     # Issuer
  maximum_expiration: 3600    # 1 hour
  leeway: 30                  # 30 seconds clock skew tolerance
  
# API Key Security
api_key_security:
  key_names:
    - "X-API-Key"
    - "Authorization"
    - "apikey"
  key_in_header: true
  key_in_query: false         # Disable for security
  key_in_body: false          # Disable for security
  hide_credentials: true      # Remove from logs
  
# Request Security Limits
request_security:
  max_request_size: 10        # 10MB
  max_header_size: 8192       # 8KB
  max_uri_length: 2048        # 2KB
  timeout: 30                 # 30 seconds
  
# Bot Detection Rules
bot_detection:
  user_agent_blacklist:
    - "*bot*"
    - "*crawler*"
    - "*spider*"
    - "*scraper*"
  
  user_agent_whitelist:
    - "Mozilla/*"             # Allow browsers
    - "okhttp/*"              # Android apps
    - "CFNetwork/*"           # iOS apps
    
# Security Monitoring
security_monitoring:
  log_failed_auth: true
  log_rate_limit_exceed: true
  log_blocked_requests: true
  log_security_events: true
  
  # Alert thresholds
  failed_auth_threshold: 10   # per minute
  rate_limit_threshold: 50    # per minute
  
# Encryption Settings
encryption:
  tls_versions:
    - "TLSv1.2"
    - "TLSv1.3"
  cipher_suites:
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES128-GCM-SHA256"
    - "ECDHE-RSA-AES256-SHA384"
    - "ECDHE-RSA-AES128-SHA256"
