services:
  db:
    image: postgres:15
    restart: always
    container_name: log430-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magasin_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: log430-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: log430-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/magasin_db"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  client1:
    build: ./client
    container_name: log430-client1
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

  client2:
    build: ./client
    container_name: log430-client2
    ports:
      - "5174:80"
    depends_on:
      - server
    restart: unless-stopped

  client3:
    build: ./client
    container_name: log430-client3
    ports:
      - "5175:80"
    depends_on:
      - server
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: log430-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    container_name: log430-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  db-data:
  prometheus-data:
  grafana-data:
  redis-data:
