apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  labels:
    app: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
      - name: kong-gateway
        image: kong-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8001
          name: admin
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8444
          name: admin-ssl
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/usr/local/kong/declarative/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        - name: KONG_LOG_LEVEL
          value: "info"
        - name: KONG_PLUGINS
          value: "bundled,prometheus"
        volumeMounts:
        - name: kong-config
          mountPath: /usr/local/kong/declarative/kong.yml
          subPath: kong.yml
        healthCheck:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-service
  labels:
    app: kong-gateway
spec:
  selector:
    app: kong-gateway
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
  - name: admin
    port: 8001
    targetPort: 8001
  - name: proxy-ssl
    port: 8443
    targetPort: 8443
  - name: admin-ssl
    port: 8444
    targetPort: 8444
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    
    services:
    - name: product-service
      url: http://product-service:3001
      routes:
      - name: product-route
        paths:
        - /api/products
    
    - name: stock-service
      url: http://stock-service:3004
      routes:
      - name: stock-route
        paths:
        - /api/stock
    
    - name: user-service
      url: http://user-service:3002
      routes:
      - name: user-route
        paths:
        - /api/users
    
    - name: store-service
      url: http://store-service:3003
      routes:
      - name: store-route
        paths:
        - /api/stores
    
    - name: sales-service
      url: http://sales-service:3005
      routes:
      - name: sales-route
        paths:
        - /api/sales
    
    - name: refund-service
      url: http://refund-service:3006
      routes:
      - name: refund-route
        paths:
        - /api/refunds
    
    upstreams:
    - name: product-service-upstream
      algorithm: round-robin
      targets:
      - target: product-service-1:3001
        weight: 100
      - target: product-service-2:3001
        weight: 100
    
    - name: stock-service-upstream
      algorithm: round-robin
      targets:
      - target: stock-service-1:3004
        weight: 100
      - target: stock-service-2:3004
        weight: 100
    
    plugins:
    - name: key-auth
      config:
        key_names:
        - X-API-Key
    
    - name: cors
      config:
        origins:
        - http://localhost:5173
        - http://localhost:3000
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Content-Type
        - X-API-Key
        - Authorization
        credentials: true
    
    - name: rate-limiting
      config:
        minute: 100
        hour: 1000
    
    - name: prometheus
      config:
        per_consumer: true
    
    consumers:
    - username: frontend-app
      keyauth_credentials:
      - key: frontend-app-key-12345
    
    - username: testing-user
      keyauth_credentials:
      - key: testing-key-xyz123
